// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package database

import (
	"context"
)

const empty = `-- name: empty :one
Select 1
`

// Empty sql query required to generate codewide database models
func (q *Queries) empty(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, empty)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}
